#Azure DevOps Pipeline YAML Code:

# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:

trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
- task: SonarQubePrepare@7
  displayName: "Prepare SonarQube"
  inputs:
    SonarQube: 'SonarQube'
    scannerMode: 'Maven'
    projectKey: 'demo'
    projectName: 'demo'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install sonar:sonar'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'



